services:
  mysql-ms1:
    image: mysql:8.0
    container_name: bloodflow-mysql-ms1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bloodflow_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_ms1_data:/var/lib/mysql
    networks:
      - bloodflow-network

  auth-service:
    build: .
    container_name: bloodflow-auth-service
    restart: always
    depends_on:
      - mysql-ms1
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-ms1:3306/bloodflow_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      BLOODFLOW_ADMIN_EMAIL: admin@bloodflow.ma
      BLOODFLOW_ADMIN_PASSWORD: Admin123@
      BLOODFLOW_ADMIN_FIRST_NAME: Super
      BLOODFLOW_ADMIN_LAST_NAME: Admin

      JWT_SECRET: bloodflow-secret-key-for-demo-change-this-later-123456789123456789
      JWT_ISSUER: bloodflow-auth-service
      JWT_AUDIENCE: bloodflow-platform

    networks:
      - bloodflow-network

volumes:
  mysql_ms1_data:

networks:
  bloodflow-network:
    driver: bridge